name: namelesslibR
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Golang Action
        uses: cedrickring/golang-action@1.6.0
        with:
          go-version: 18
          cache: go
      - name: install gomobile
        run : go install golang.org/x/mobile/cmd/gomobile@latest
        
      - name : goland init go mobile
        run : gomobile init
        
      - name : gomobile build aar
        run : gomobile bind -v -o namelesslibR.aar -target=android ./
